/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektView;

import main_package.exceptions_.NumberoutException;
import main_package.exceptions_.StringoutException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.concurrent.TimeUnit;
import main_package.MainClassVirtualManager;
import org.javatuples.Triplet;

/**
 *
 * @author Adrian
 */
public class Employees extends javax.swing.JFrame {
    private MainClassVirtualManager employees_view;
    private DefaultTableModel model_of_table;
    private final String class_name = this.getClass().getName().substring(this.getClass().getName().lastIndexOf('.') + 1);
    private int Update_index = 0;
    /**
     * Creates new form Employees
     */
    public Employees(){
        try {
            initComponents();
            updateToList.setVisible(false);
            employees_view = new MainClassVirtualManager(class_name);
            model_of_table = (DefaultTableModel) jTable2.getModel();
            employees_view.startThreads(Prediction, class_name);
            TimeUnit.MILLISECONDS.sleep(250);
            employees_view.refreshView(model_of_table, class_name);
        } catch (InterruptedException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JTextField();
        Surname = new javax.swing.JTextField();
        Salary = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateToList = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Prediction = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zarządzanie pracownikami");
        setBackground(new java.awt.Color(0, 102, 204));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Imię", "Nazwisko", "Pensja", "Typ umowy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);
        jTable2.getAccessibleContext().setAccessibleName("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));

        Name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Name.setName("Name"); // NOI18N
        Name.setOpaque(false);

        Surname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Salary.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        addButton.setBackground(new java.awt.Color(0, 102, 153));
        addButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Dodaj");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateToList.setBackground(new java.awt.Color(0, 102, 153));
        updateToList.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        updateToList.setForeground(new java.awt.Color(255, 255, 255));
        updateToList.setText("Uaktualnij");
        updateToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateToListActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "o pracę", "zlecenie", "zlecenie (studenci)", "o dzieło" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setText("Rodzaj umowy");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setText("Imię");

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setText("Nazwisko");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setText("Pensja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Surname)
            .addComponent(Name)
            .addComponent(Salary)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateToList, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateToList)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Name.getAccessibleContext().setAccessibleName("Name");
        Surname.getAccessibleContext().setAccessibleName("Surname");
        Salary.getAccessibleContext().setAccessibleName("Salary");

        deleteButton.setBackground(new java.awt.Color(0, 102, 153));
        deleteButton.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Usuń");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(0, 102, 153));
        UpdateButton.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Aktualizuj");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Przewidywany zysk:");

        Prediction.setBackground(new java.awt.Color(255, 255, 153));
        Prediction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Prediction, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Prediction, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        employees_view.terminateThreads();
        this.dispose();
        new MainForm().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try{
            String name = Name.getText();
            if (!name.matches("[a-zA-ZąćęśłóżźńĄĆĘÓŁŚŃŻŹ]+") || "".equals(name))
                throw new StringoutException();
            String surname = Surname.getText();
            if (!surname.matches("[a-zA-ZąćęśłóżźńĄĆĘŚÓŁŃŻŹ]+") || "".equals(surname))
                throw new StringoutException();
            if (!Salary.getText().matches("[0-9]+") || "".equals(Salary.getText()) )
                throw new NumberoutException();
            int salary = Integer.parseInt(Salary.getText());
            
            Object selectedItem = jComboBox1.getSelectedItem();
            String selectedItemStr = selectedItem.toString();
            String type = this.convertfromCombotoyamlformat(selectedItemStr);
            employees_view.add(name, surname, salary, type);
            Name.setText("");
            Surname.setText("");
            Salary.setText("");
            //TimeUnit.MILLISECONDS.sleep(500);
            employees_view.refreshView(model_of_table, class_name);
        }
        catch (StringoutException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nieprawne dane!!! Pola imię i nazwisko mogą zawierać tylko litery", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch (NumberoutException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nieprawne dane!!! Pole pensja może zawierać tylko liczby", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        int row_index = jTable2.getSelectedRow();
        int rows_index[] = jTable2.getSelectedRows();
        try{ 
            if (row_index==-1 || rows_index.length==0){
                throw new ArrayIndexOutOfBoundsException();
            }
            else{               
                if (row_index!=-1 && rows_index.length==1){ 
                    employees_view.delete(row_index, class_name);
                    //TimeUnit.MILLISECONDS.sleep(500);
                    employees_view.refreshView(model_of_table, class_name);
                }
                else{
                    for (int i=0; i<rows_index.length; i++){
                        employees_view.delete(rows_index[i]-i, class_name);
                    }
                    //TimeUnit.MILLISECONDS.sleep(500);
                    employees_view.refreshView(model_of_table, class_name);
                }
            }           
        }
        catch (ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Wybierz pracownika do usunięcia!!!", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Wybierz pracownika do usunięcia!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        int row_index = jTable2.getSelectedRow();
        if (row_index==-1){
            JOptionPane.showMessageDialog(null, "Wybierz pracownika do aktualizacji!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Update_index = row_index;
            Triplet<javax.swing.JTextField,javax.swing.JTextField,javax.swing.JTextField> triplet = Triplet.with(Name, Surname, Salary);
            //javax.swing.JLabel[] x = {Type, Title, Cost};
            employees_view.writeDataToTextField(Update_index, triplet,0);
            addButton.setVisible(false);
            updateToList.setVisible(true);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void updateToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateToListActionPerformed
        // TODO add your handling code here:
            
            try{
                String name = Name.getText();
                if (!name.matches("[a-zA-ZąćęśłóżźńĄĆŚĘÓŁŃŻŹ]+") || "".equals(name))
                    throw new StringoutException();
                String surname = Surname.getText();
                if (!surname.matches("[a-zA-ZąćęśłóżźńĄĆŚĘÓŁŃŻŹ]+") || "".equals(surname))
                    throw new StringoutException();
                if (!Salary.getText().matches("[0-9]+") || "".equals(Salary.getText()) )
                    throw new NumberoutException();
                int salary = Integer.parseInt(Salary.getText());
                
                Object selectedItem = jComboBox1.getSelectedItem();
                String selectedItemStr = selectedItem.toString();
                String type = this.convertfromCombotoyamlformat(selectedItemStr);
                employees_view.updateList(Update_index, name, surname, salary, type);
                Name.setText("");
                Surname.setText("");
                Salary.setText("");
                employees_view.refreshView(model_of_table, class_name);
                addButton.setVisible(true);
                updateToList.setVisible(false);
            }
            catch (StringoutException ex) {
                Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Nieprawne dane!!! Pola imię i nazwisko mogą zawierać tylko litery", "Error", JOptionPane.ERROR_MESSAGE);
            } 
            catch (NumberoutException ex) {
                Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Nieprawne dane!!! Pole pensja może zawierać tylko liczby", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_updateToListActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    private String convertfromCombotoyamlformat(String param){
        switch (param){
            case "o pracę": 
                return "Praca";
            case "zlecenie":
                return "Zlecenie";
            case "zlecenie (studenci)":
                return "Zlecenie (studenci)";
            case "o dzieło":
                return "Dzieło";
            default:
                return "";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JLabel Prediction;
    private javax.swing.JTextField Salary;
    private javax.swing.JTextField Surname;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton updateToList;
    // End of variables declaration//GEN-END:variables
}
