/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektView;

import main_package.threads_.ReadWrite_from_yaml_Charges;
import main_package.threads_.Threads_main_class;
import main_package.model.Charges_struct_yaml;
import main_package.controller.Charges_operations;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class Current_charges extends javax.swing.JFrame {
    private Charges_operations charges_view;
    private DefaultTableModel model_of_table;
    private Threads_main_class new_read_thread;
    private int Update_index = 0;
    /**
     * Creates new form Current_charges
     */
    public Current_charges() {
        initComponents();
        try {

            UpdateToList.setVisible(false);  
            charges_view = new Charges_operations();
            model_of_table = (DefaultTableModel) Table_charges.getModel();
            new_read_thread = new ReadWrite_from_yaml_Charges("charges", charges_view);
            new_read_thread.start();
            
            TimeUnit.MILLISECONDS.sleep(500);
            this.refreshView(model_of_table); 
        } catch (InterruptedException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        UpdateToList = new javax.swing.JButton();
        Cost = new javax.swing.JTextField();
        Type = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_charges = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bieżące opłaty");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dodawanie/edytowanie opłat", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Monotype Corsiva", 1, 16), new java.awt.Color(0, 51, 51))); // NOI18N

        addButton.setText("Dodaj");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        UpdateToList.setText("Uaktualnij");
        UpdateToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateToListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cost)
                    .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(UpdateToList)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(Cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(UpdateToList))
                .addContainerGap())
        );

        deleteButton.setText("Usuń");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Aktualizacja");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        Table_charges.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Opłata", "Koszt"
            }
        ));
        jScrollPane1.setViewportView(Table_charges);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(updateButton)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        new MainForm().setVisible(true);
        new_read_thread.terminate();
        charges_view.write_to_yaml();
        this.dispose();

    }//GEN-LAST:event_formWindowClosed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String type = Type.getText();
        int cost = Integer.parseInt(Cost.getText());
        charges_view.addCharge(type, cost);
        Type.setText("");
        Cost.setText("");
        this.refreshView(model_of_table);
    }//GEN-LAST:event_addButtonActionPerformed

    private void UpdateToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateToListActionPerformed
        // TODO add your handling code here:
        addButton.setVisible(true);
        UpdateToList.setVisible(false);  
        String type = Type.getText();
        int cost =Integer.parseInt(Cost.getText());
        charges_view.updateCharge(Update_index, type, cost);
        Type.setText("");
        Cost.setText("");
        this.refreshView(model_of_table);        
    }//GEN-LAST:event_UpdateToListActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int row_index = Table_charges.getSelectedRow();
        if (row_index==-1){
            JOptionPane.showMessageDialog(null, "Wybierz opłatę do aktualizacji!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Update_index = row_index;
            Charges_struct_yaml chargeToUpdate = charges_view.getCharge(row_index);
            Type.setText(chargeToUpdate.getType());
            Cost.setText(Integer.toString(chargeToUpdate.getCost()));
            addButton.setVisible(false);
            updateButton.setVisible(true);
        }        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel model_of_table = (DefaultTableModel) jTable2.getModel();
        int row_index = Table_charges.getSelectedRow();
        //System.out.println(row_index);
        int rows_index[] = Table_charges.getSelectedRows();
        //System.out.println(rows_index.length);
        try{ 
            if (row_index==-1 || rows_index.length==0){
                throw new ArrayIndexOutOfBoundsException();
            }
            else{               
                if (row_index!=-1 && rows_index.length==1){ 
                    //System.out.println(row_index);
                    //model_of_table.removeRow(row_index);
                    charges_view.deleteCharge(row_index);
                    //TimeUnit.MILLISECONDS.sleep(500);
                    this.refreshView(model_of_table);
                }
                else{
                    for (int i=0; i<rows_index.length; i++){
                        //model_of_table.removeRow(rows_index[i]-i);
                        charges_view.deleteCharge(rows_index[i]-i);

                        //System.out.println(rows_index[i]-i);
                    }
                    //TimeUnit.MILLISECONDS.sleep(500);
                    this.refreshView(model_of_table);
                }
            }           
        }
        catch (ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Wybierz pracownika do usunięcia!!!", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Wybierz pracownika do usunięcia!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void refreshView(DefaultTableModel model_of_table){
        //model_of_table.getDataVector().clear();
        Charges_struct_yaml charge;
        for (int i=0; i<charges_view.getCount(); i++){
            charge = charges_view.getCharge(i);
            model_of_table.addRow(new Object[]{charge.getType(), charge.getCost()});
            System.out.println(charge.getType() +  " " + charge.getCost());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Current_charges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Current_charges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Current_charges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Current_charges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Current_charges().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cost;
    private javax.swing.JTable Table_charges;
    private javax.swing.JTextField Type;
    private javax.swing.JButton UpdateToList;
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
