/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektView;

import main_package.exceptions_.NumberoutException;
import main_package.exceptions_.StringoutException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main_package.MainClassVirtualManager;
import org.javatuples.Pair;

/**
 *
 * @author Adrian
 */
public class Charges extends javax.swing.JFrame {
    private MainClassVirtualManager charges_view;
    private DefaultTableModel model_of_table;
    private final String class_name = this.getClass().getName().substring(this.getClass().getName().lastIndexOf('.') + 1);
    private int Update_index = 0;
    /**
     * Creates new form Charges
     */
    public Charges() {
        initComponents();
        try {
            updateToList.setVisible(false);  
            charges_view = new MainClassVirtualManager(class_name);
            model_of_table = (DefaultTableModel) Table_charges.getModel();   
            charges_view.startThreads(Prediction, class_name);
            
            TimeUnit.MILLISECONDS.sleep(200);
            charges_view.refreshView(model_of_table, class_name); 
        } catch (InterruptedException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanel = new javax.swing.JScrollPane();
        Table_charges = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Type = new javax.swing.JTextField();
        Cost = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateToList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Prediction = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zarządzanie opłatami");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Table_charges.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Opłata", "Koszt"
            }
        ));
        jScrollPanel.setViewportView(Table_charges);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 102, 102)));

        addButton.setBackground(new java.awt.Color(0, 102, 153));
        addButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Dodaj");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateToList.setBackground(new java.awt.Color(0, 102, 153));
        updateToList.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        updateToList.setForeground(new java.awt.Color(255, 255, 255));
        updateToList.setText("Uaktualnij");
        updateToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateToListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Koszt");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Opłata");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cost, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(Type)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateToList)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateToList)
                .addGap(19, 19, 19))
        );

        deleteButton.setBackground(new java.awt.Color(0, 102, 153));
        deleteButton.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Usuń");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(0, 102, 153));
        updateButton.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Aktualizacja");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Przewidywany zysk:");

        Prediction.setBackground(new java.awt.Color(255, 255, 153));
        Prediction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Prediction, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Prediction, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //new MainForm().setVisible(true);
        charges_view.terminateThreads();
        this.dispose();
        MainForm newMain = new MainForm();
        newMain.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try{
            String type = Type.getText();
            if (!type.matches("[a-zA-ZąćęśłóżźńĄĆĘÓŁŃŻŹ]+") || "".equals(type))
                throw new StringoutException();    
            if (!Cost.getText().matches("[0-9]+") || "".equals(Cost.getText()))
                throw new NumberoutException();
            int cost = Integer.parseInt(Cost.getText());
            charges_view.add(type, cost, class_name);
            Type.setText("");
            Cost.setText("");
            charges_view.refreshView(model_of_table, class_name);
        }
        catch (StringoutException ex) {
            Logger.getLogger(Charges.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nieprawne dane! Pole opłata może zawierać tylko litery", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch (NumberoutException ex) {
            Logger.getLogger(Charges.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nieprawne dane! Pole koszt może zawierać tylko liczby", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateToListActionPerformed
        // TODO add your handling code here:
        try{
            
            String type = Type.getText();
            if (!type.matches("[a-zA-ZąćęśłóżźńĄĆĘÓŁŃŻŹ]+") || "".equals(type))
                throw new StringoutException();    
            if (!Cost.getText().matches("[0-9]+") || "".equals(Cost.getText()))
                throw new NumberoutException();
            int cost =Integer.parseInt(Cost.getText());
            charges_view.updateList(Update_index, type, cost, class_name);
            Type.setText("");
            Cost.setText("");
            charges_view.refreshView(model_of_table, class_name); 
            addButton.setVisible(true);
            updateToList.setVisible(false);  
        }
        catch (StringoutException ex) {
            Logger.getLogger(Charges.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nieprawne dane! Pole opłata może zawierać tylko litery", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch (NumberoutException ex) {
            Logger.getLogger(Charges.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nieprawne dane! Pole koszt może zawierać tylko liczby", "Error", JOptionPane.ERROR_MESSAGE);
        }          
    }//GEN-LAST:event_updateToListActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row_index = Table_charges.getSelectedRow();
        //System.out.println(row_index);
        int rows_index[] = Table_charges.getSelectedRows();
        //System.out.println(rows_index.length);
        try{ 
            if (row_index==-1 || rows_index.length==0){
                throw new ArrayIndexOutOfBoundsException();
            }
            else{               
                if (row_index!=-1 && rows_index.length==1){ 
                    //System.out.println(row_index);
                    //model_of_table.removeRow(row_index);
                    charges_view.delete(row_index, class_name);
                    //TimeUnit.MILLISECONDS.sleep(500);
                    charges_view.refreshView(model_of_table, class_name);
                }
                else{
                    for (int i=0; i<rows_index.length; i++){
                        //model_of_table.removeRow(rows_index[i]-i);
                        charges_view.delete(rows_index[i]-i, class_name);

                        //System.out.println(rows_index[i]-i);
                    }
                    //TimeUnit.MILLISECONDS.sleep(500);
                    charges_view.refreshView(model_of_table, class_name);
                }
            }           
        }
        catch (ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Wybierz opłatę do usunięcia!!!", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Wybierz opłatę do usunięcia!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int row_index = Table_charges.getSelectedRow();
        if (row_index==-1){
            JOptionPane.showMessageDialog(null, "Wybierz opłatę do aktualizacji!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Update_index = row_index;
            Pair<javax.swing.JTextField ,javax.swing.JTextField> pair = Pair.with(Type, Cost);
            charges_view.writeDataToTextField(Update_index, class_name, pair);
            
            addButton.setVisible(false);
            updateToList.setVisible(true);
        }        
    }//GEN-LAST:event_updateButtonActionPerformed
                                                                                                                                              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Charges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Charges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Charges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Charges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Charges().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cost;
    private javax.swing.JLabel Prediction;
    private javax.swing.JTable Table_charges;
    private javax.swing.JTextField Type;
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateToList;
    // End of variables declaration//GEN-END:variables
}
